// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnwrojnsxfefgwvypgdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJud3Jvam5zeGZlZmd3dnlwZ2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDczMzMsImV4cCI6MjA2NDUyMzMzM30.o45AW5a6uV0o6cXL0fgOwICYT-BZSVogY6OXnCyrE3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);